Instrument `/record`
kb-dk/ds-present pull request #138
Opened 2024-03-22 08:57 UTC by tokee

This pull request adds always-on instrumentation of the `/record` endpoint, logging the time spend on retrieval and transformation of the record data. The stats are bucketed in origin+view, making it possible to pinpoint heavy transformations and/or data sources.

The endpoint `/monitor/status` has been expanded with the overall stats. Testing can be done by starting the service on the developer network (so that it can reach a working `ds-storage`), issuing some requests to `/record` with different views and calling
```shell
curl -s 'http://localhost:9073/ds-present/v1/monitor/status' | jq -r .stats
```
which should yield something like
```
getRecord(3records, 117ms/records, 8records/s, max=225ms, last52ms, [
  access(3checks, 0ms/checks, 10421checks/s, max=0ms, last0ms),
  origin_ds.tv(, [
    json-ld(1record, 207ms/record, 4record/s, max=207ms, last207ms, [
      retrieve(1record, 123ms/record, 8record/s, max=123ms, last123ms),
      transform(1record, 82ms/record, 12record/s, max=82ms, last82ms)
    ]),
    solrjson(2record, 63ms/record, 15record/s, max=76ms, last51ms, [
      retrieve(2record, 14ms/record, 68record/s, max=14ms, last14ms),
      transform(2record, 49ms/record, 20record/s, max=61ms, last36ms)
    ])
  ])
])
```

2024-03-22 12:51 UTC, VictorHarbo requested changes
I can't really put my finger on anything here. 

Is it possible in any way to do the same kind of statistics per record in the `/records`-endpoint? If so, should that be a part of this PR or another task?

2024-03-22 13:12 UTC, tokee commented
> I can't really put my finger on anything here.
> 
> Is it possible in any way to do the same kind of statistics per record in the `/records`-endpoint? If so, should that be a part of this PR or another task?

I looked and it is not trivial to get right due to the whole streaming-from-storage, so I decided to keep it out of this pull request. I'll add that as another issue.

2024-03-22 13:14 UTC, tokee commented on src/main/java/dk/kb/present/DSOrigin.java
> +                    getView(format).apply(record));
I fully understand that this can be tricky to read. Should I change it to "less clever but more readable" code?

2024-03-25 06:13 UTC, VictorHarbo commented on src/main/java/dk/kb/present/DSOrigin.java
> +                    getView(format).apply(record));
I am fine with keeping it as it is now. lamdas are here to be used!

2024-03-25 06:14 UTC, merged