Dra 659 paralleliser transforationer
kb-dk/ds-present pull request #159
Opened 2024-07-03 14:07 UTC by davidgrove73

2024-07-04 06:13 UTC, VictorHarbo requested changes
Looks good overall. However, when I am running individual test classes they fail due to initialization errors. Could you please make sure that all `transformer` test classes can be run individually from the IDE. The same goes for the class `ViewTest`.  

I would also like some kind of test of the metadata map not getting messed up. Maybe you could add a test in ViewTest, with multiple test records being processed in parallel and checking the solr transformation for value: `internal_storage_mTime` as te storage value can be set directly on DsRecords with something like this ` DsRecordDto recordDto = new DsRecordDto().data(pvica).id("test.id").mTime(1701261949625000L);`

2024-07-05 09:10 UTC, davidgrove73 commented
ServiceConfig needed to be initialized before the tests are run. Not sure if this is the best way of doing it and I am a little unsure of when static variables are initialized when tests are run.

An test for testing parallel processing of records have been added to views.

2024-07-05 12:09 UTC, VictorHarbo requested changes
I like the tests! Small suggestion on how the conf is loaded.

2024-07-05 13:55 UTC, davidgrove73 commented on src/test/java/dk/kb/present/solr/EmbeddedSolrTest.java
> +        ServiceConfig.initialize(CONFIG);
I think you are right, and ServiceConfig.initialize handles missing config files as well.

2024-07-08 08:31 UTC, merged