Dra 728 implement holdback filter
kb-dk/ds-present pull request #160
Opened 2024-07-04 12:00 UTC by VictorHarbo

First implementation of DR holdback filter. Excel sheets are present in aegis for testing. We should discuss where these should be placed on the devel server. (Eventhough the PR says 21 files changed, the 9 of these are test classes)

Hard to test on devel, as the data isnt in preservica stage yet. Please give code a thorough review and comment anything that isn't clear in the documentation as well

BEFORE DOING ANYTHING: Update aegis by

1. Pulling aegis
2. Removing internal_test_files dir in ds-present
3. run kb init in ds-present.

2024-07-05 11:02 UTC, thomasegense requested changes
Looks very solid code and united+embedded solr tested also.
Only major thing is separating all the POI work every time processing a record into a simple java data class and use this when processing the records.

I will delay running with the unit tests for the  review until this refactoring has been submitted.
Also the performance test will be run (another Jira) and this has been solved.

2024-07-05 13:13 UTC, VictorHarbo commented on src/main/java/dk/kb/present/HoldbackDatePicker.java
> +     *         In the format: yyyy-MM-dd'T'HH:mm:ssZ
Typo. Normal UTC is also used in the code

2024-07-05 13:13 UTC, VictorHarbo commented on src/main/java/dk/kb/present/HoldbackDatePicker.java
> +            log.error("Holdback cannot be calculated for records that are not from origins 'ds.radio' or 'ds.tv'." +
Changed to InternalServiceException

2024-07-05 13:13 UTC, VictorHarbo commented on conf/ds-present-environment.yaml.SAMPLE
> +# when the files have been injected from aegis. However, full paths can be specief as well.
fixed

2024-07-05 13:13 UTC, VictorHarbo commented on src/main/java/dk/kb/present/HoldbackDatePicker.java
> +     * Calculate holdback for a TV record by comparing values in the record to the DR providede schemas.
fixed

2024-07-05 13:17 UTC, VictorHarbo commented on src/main/resources/xslt/preservica2schemaorg.xsl
> +    <!-- Holdback date included here. Holdbac purpose is only included for video objects, therefor it is done in the
fixed

2024-07-11 07:50 UTC, thomasegense requested changes
Few minor things.

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/HoldbackDatePicker.java
> +import org.apache.poi.ss.usermodel.Cell;
Clean up unused imports. (POI logic seperated from business logic now)

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/HoldbackDatePicker.java
> +    private static XSSFSheet purposeMatrixSheetOld;
clean up

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/FormIndexSheet.java
> +public class FormIndexSheet {
Would like a little java class doc.

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/PurposeMatrixSheet.java
> +public class PurposeMatrixSheet {
Little javadoc wanted

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/PurposeMatrixSheet.java
> +    private final int NUMBER_OF_COLUMNS = 18; // Number of columns in the sheet
Can you validate this and throw exception if not correct. Means Excel sheet is out of sync with code.

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/holdback/PurposeMatrixSheet.java
> +        log.info("Initialized PurposeMatrixSheet with the following values: \n" +
This should be moved to the toString() method  for the class. This is not just a log statement, but a representation of the class.

 And here just call toString() to log it.
Maybe same situation for the other sheet classes.

2024-07-11 07:50 UTC, thomasegense commented on src/main/java/dk/kb/present/webservice/ContextListener.java
> +            HoldbackDatePicker.init();
A few lines down. end bracked } for method not formatted correct. Move to next line. I know it is not part of this review...

2024-07-11 12:47 UTC, merged