Wok 621 xslt to jsonld
kb-dk/ds-present pull request #17
Opened 2023-03-20 14:02 UTC by VictorHarbo

This PR contains XSLT that transforms MODS to Schema.org JSON-LD.

2023-03-23 15:02 UTC, tokee requested changes
Only one real issue: Injection of the imageserver.

2023-03-23 15:02 UTC, tokee commented on src/test/java/dk/kb/present/transform/XSLTSchemaDotOrgTransformerTest.java
> +     */
I understand what is happening here. It is useful and at the same time a bit temptation to just regenerate the test files without inspecting them to see if the change was benign.

Let's discuss this face2face.

2023-03-27 10:28 UTC, VictorHarbo commented
Testfiles and XSLT has been updated and your generalized parameter injection has been merged. There are some old unittest files present, that are to be deleted with the cleanup being done in branch WOK_640

2023-03-27 10:45 UTC, tokee requested changes
Grasping at straws here by asking for nicer URLs.

2023-03-27 10:45 UTC, tokee commented on src/test/resources/schemaOrgJsonTestFiles/schemaOrg_40221e30-1414-11e9-8fb8-00505688346e.json
> +{"@context":["http:\/\/schema.org\/",{"kb":"http:\/\/kb.dk\/vocabs\/","relator":"https:\/\/id.loc.gov\/vocabulary\/relators\/"}],"@type":"Photograph","id":"40221e30-1414-11e9-8fb8-00505688346e","url"
The image URL has a double slash: https://example.com/imageserver//DAMJP2/DAM/Samlingsbilleder/0000/624/420/KE070592 . Technically it works, but it ain't pretty. I know it's my fault for putting the slash in the properties, but maybe remove it from the properties and add a comment saying it should not end in slash? Or the fancy version: Remove the slash in the XSLT if it is present?

2023-03-27 10:58 UTC, tokee requested changes
Typo!

2023-03-27 10:58 UTC, tokee commented on conf/ds-present-behaviour.yaml
> +  # This has to be set before image URLs are working. imageserver has to pe set without trailing slash as this is currently handled by the XSLT transformation
Plese mirror the `p` vertically.

2023-03-27 11:00 UTC, tokee approved these changes

2023-03-27 11:00 UTC, merged