DISC-12 abstract imageserver
kb-dk/ds-present pull request #26
Opened 2023-08-17 12:39 UTC by tokee

This moves specification of the imageserver URL used as injection to the transformers to a central property in the configuration flow, as opposed to duplicating the URL.

2023-08-18 06:26 UTC, VictorHarbo approved these changes
LGTM!

2023-08-18 12:21 UTC, tokee commented
Ready for review.

2023-08-18 12:26 UTC, VictorHarbo requested changes
Unittest fails

2023-08-18 12:26 UTC, VictorHarbo commented on src/test/java/dk/kb/present/config/ServiceConfigTest.java
> +                yaml.getSubMap("config.collections[4].samlingsbilleder.views[3].SolrJSON").
This test throws an IlligalArgumentException on line 78.

2023-08-18 12:27 UTC, VictorHarbo commented on src/test/java/dk/kb/present/config/ServiceConfigTest.java
> +                yaml.getSubMap("config.collections[4].samlingsbilleder.views[3].SolrJSON").
Sorry! I was to quick!

2023-08-18 16:38 UTC, tokee commented
I've put this on hold again until I have it fully running on the devel server.

2023-08-21 06:17 UTC, VictorHarbo approved these changes
I've looked at the code again. However I missed that you put it on hold.

2023-08-21 10:46 UTC, tokee commented
Setting this to active as the overriding issue has been resolved. Calling

http://<internaldevelserver>:10001/ds-present/v1/records?collection=samlingsbilleder&maxRecords=1&format=SolrJSON

demonstrates working injection. Note that `<internaldevelserver` must be replaced with the real server name.

2023-08-21 11:16 UTC, VictorHarbo commented
> Setting this to active as the overriding issue has been resolved. Calling
> 
> http://:10001/ds-present/v1/records?collection=samlingsbilleder&maxRecords=1&format=SolrJSON
> 
> demonstrates working injection. Note that `<internaldevelserver` must be replaced with the real server name.

The injection works. However it injects our IIIF server where the test corpus uses the IIP server. Will you fix this here or should i do that on the branch I am working on?

2023-08-21 11:36 UTC, merged