Disc 130 add origin field
kb-dk/ds-present pull request #45
Opened 2023-09-01 12:00 UTC by VictorHarbo

2023-09-04 11:38 UTC, tokee requested changes
A few small things are noted in the comments, but the big thing missing is a search for `recordBase` in the full code and a subsequent change to `origin`.

Pro tip: Ide IDEA to refactor the `Storage.java` and similar base classes or interfaces: It will suggest a similar rename of the arguments in inheriting classes.

2023-09-04 11:38 UTC, tokee commented on src/main/java/dk/kb/present/View.java
> +    public View(YAML conf, String originFromCollection) {
Remember JavaDoc

2023-09-04 11:38 UTC, tokee commented on src/main/resources/xslt/mods2solr.xsl
> +       <xsl:param name="origin"/>
What about the two schema.org XSLTs?

2023-09-04 11:38 UTC, tokee commented on src/test/java/dk/kb/present/TestUtil.java
> +		System.out.println(prettyJsonString);
Same code as `prettyPrintSolrJsonFromPreservica`, right? Time for a helper method :-)

2023-09-05 05:54 UTC, VictorHarbo commented on src/main/resources/xslt/mods2solr.xsl
> +       <xsl:param name="origin"/>
Yes, I'll add them as identifiers

2023-09-05 07:05 UTC, tokee requested changes
Looks good so far, but still needs a "Find in Files" for `recordBase`.

2023-09-05 07:17 UTC, tokee requested changes
That was fast!

`DSStorage` still has some leftovers for `base` and `DSStorageFactory` also used base in the setup, so changes to that one requires updates to the YAML (remember to check is `aegis` also needs an update).

2023-09-05 08:37 UTC, merged