Ename More Like This support
kb-dk/ds-present pull request #59
Opened 2023-10-11 14:00 UTC by tokee

This pull request tweaks the `text_general` specification to support efficient highlighting and More Like This. It also add a `MoreLikeThisHandler` so `solrconfig.xml` for proper support with distributed search.

The functionality can be tested by updating the configuration for an existing Solr setup with DS-content, then calling

```
curl -s 'http://localhost:10007/solr/ds/mlt' -d 'mlt.interestingTerms=list' -d 'mlt.fl=text' -d "q=*:*" -d 'fl=id,title' -d 'mlt.match.include=true' -d 'mlt.mintf=2' -d 'mlt.mindf=2' -d 'mlt.boost=true' -d 'mlt.maxntp=100000' -d 'mlt.qf=text' -d 'mlt.maxqt=10' -d 'mlt.maxdfpct=50' 
```

This should show
* The origo document under `match`
* 10 related documents under `response`
* The terms used for searching the related documents under `interestingTerms`

2023-10-12 08:54 UTC, VictorHarbo requested changes
Two minor comments

2023-10-13 07:41 UTC, tokee commented on src/test/resources/solr/dssolr/conf/solrconfig.xml
> +      <str name="mlt.mintf">2</str>
More Like This does not have a problem with extra field - well, besides a potential noise problem - so for now I'd prefer if we err to the "many fields" side. I am sure we will tweak it for better results when we have a proper corpus running.

2023-10-13 07:42 UTC, tokee commented on src/test/resources/solr/dssolr/conf/solrconfig.xml
> +      <str name="mlt.mintf">2</str>
I have added the fields you suggested BTW. Thanks!

2023-10-13 08:04 UTC, VictorHarbo approved these changes
LGTM!

2023-10-13 08:04 UTC, merged